import { assets } from '../assets/assets'; 

export const products = [
  {
    _id: "1",
    name: "Classic White T-Shirt",
    description: "Soft cotton white t-shirt for everyday wear.",
    price: 499,
    images: [assets.tshirt1, assets.tshirt2, assets.tshirt1, assets.tshirt2],
    category: "Clothing",
    subCategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL"],
    date: "2025-06-19T10:00:00Z",
    bestseller: true
  },
  {
    _id: "2",
    name: "Blue Denim Jeans",
    description: "Classic blue denim jeans with slim fit.",
    price: 1299,
    images: [assets.denim1, assets.denim2],
    category: "Clothing",
    subCategory: "Jeans",
    sizes: ["28", "30", "32", "34", "36"],
    date: "2025-06-18T10:00:00Z",
    bestseller: false
  },
  {
    _id: "3",
    name: "Sports Running Shoes",
    description: "Breathable running shoes for athletes.",
    price: 2199,
    images: [assets.shoes1, assets.shoes2],
    category: "Footwear",
    subCategory: "Running Shoes",
    sizes: ["7", "8", "9", "10"],
    date: "2025-06-17T10:00:00Z",
    bestseller: true
  },
  {
    _id: "4",
    name: "Leather Wallet",
    description: "Premium leather wallet with card slots.",
    price: 899,
    images: [assets.wallet1, assets.wallet2],
    category: "Accessories",
    subCategory: "Wallets",
    sizes: [],
    date: "2025-06-16T10:00:00Z",
    bestseller: false
  },
  {
    _id: "5",
    name: "Analog Wrist Watch",
    description: "Stylish analog watch for men.",
    price: 1599,
    images: [assets.watch1, assets.watch2],
    category: "Accessories",
    subCategory: "Watches",
    sizes: [],
    date: "2025-06-15T10:00:00Z",
    bestseller: true
  },
  {
    _id: "6",
    name: "Yoga Mat",
    description: "Non-slip yoga mat with grip texture.",
    price: 749,
    images: [assets.yogamat1, assets.yogamat2],
    category: "Fitness",
    subCategory: "Mats",
    sizes: ["Standard"],
    date: "2025-06-14T10:00:00Z",
    bestseller: false
  },
  {
    _id: "7",
    name: "Cotton Shorts",
    description: "Comfortable cotton shorts for summer.",
    price: 699,
    images: [assets.shorts1, assets.shorts2],
    category: "Clothing",
    subCategory: "Shorts",
    sizes: ["S", "M", "L"],
    date: "2025-06-13T10:00:00Z",
    bestseller: true
  },
  {
    _id: "8",
    name: "Wireless Earbuds",
    description: "Bluetooth earbuds with noise cancellation.",
    price: 2799,
    images: [assets.earbuds1, assets.earbuds2],
    category: "Electronics",
    subCategory: "Audio",
    sizes: [],
    date: "2025-06-12T10:00:00Z",
    bestseller: false
  },
  {
    _id: "9",
    name: "Black Hoodie",
    description: "Casual black hoodie with fleece lining.",
    price: 1499,
    images: [assets.hoodie1, assets.hoodie2],
    category: "Clothing",
    subCategory: "Hoodies",
    sizes: ["M", "L", "XL"],
    date: "2025-06-11T10:00:00Z",
    bestseller: true
  },
  {
    _id: "10",
    name: "Stainless Steel Water Bottle",
    description: "Eco-friendly and reusable bottle.",
    price: 399,
    images: [assets.bottle1, assets.bottle2],
    category: "Home",
    subCategory: "Kitchen",
    sizes: ["500ml", "750ml"],
    date: "2025-06-10T10:00:00Z",
    bestseller: false
  },
  {
    _id: "11",
    name: "Wireless Mouse",
    description: "Ergonomic mouse with silent clicks.",
    price: 599,
    images: [assets.mouse1, assets.mouse2],
    category: "Electronics",
    subCategory: "Computer Accessories",
    sizes: [],
    date: "2025-06-09T10:00:00Z",
    bestseller: true
  },
  {
    _id: "12",
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass.",
    price: 1399,
    images: [assets.speaker1, assets.speaker2],
    category: "Electronics",
    subCategory: "Speakers",
    sizes: [],
    date: "2025-06-08T10:00:00Z",
    bestseller: false
  },
  {
    _id: "13",
    name: "Formal Shirt",
    description: "Slim fit formal shirt for men.",
    price: 999,
    images: [assets.formalshirt1, assets.formalshirt2],
    category: "Clothing",
    subCategory: "Shirts",
    sizes: ["M", "L", "XL", "XXL"],
    date: "2025-06-07T10:00:00Z",
    bestseller: true
  },
  {
    _id: "14",
    name: "Laptop Backpack",
    description: "Water-resistant backpack with USB port.",
    price: 1899,
    images: [assets.backpack1, assets.backpack2],
    category: "Accessories",
    subCategory: "Bags",
    sizes: [],
    date: "2025-06-06T10:00:00Z",
    bestseller: false
  },
  {
    _id: "15",
    name: "Sunglasses",
    description: "UV-protected stylish sunglasses.",
    price: 599,
    images: [assets.sunglasses1, assets.sunglasses2],
    category: "Accessories",
    subCategory: "Eyewear",
    sizes: [],
    date: "2025-06-05T10:00:00Z",
    bestseller: true
  },
  {
    _id: "16",
    name: "Graphic Printed T-Shirt",
    description: "Trendy t-shirt with cool graphics.",
    price: 699,
    images: [assets.graphictee1, assets.graphictee2],
    category: "Clothing",
    subCategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL"],
    date: "2025-06-04T10:00:00Z",
    bestseller: false
  },
  {
    _id: "17",
    name: "Cotton Face Mask",
    description: "Reusable and washable face masks.",
    price: 199,
    images: [assets.mask1, assets.mask2],
    category: "Health",
    subCategory: "Masks",
    sizes: ["Adult", "Kids"],
    date: "2025-06-03T10:00:00Z",
    bestseller: true
  },
  {
    _id: "18",
    name: "Smart Fitness Band",
    description: "Track your steps, heart rate, and sleep.",
    price: 2499,
    images: [assets.fitnessband1, assets.fitnessband2],
    category: "Electronics",
    subCategory: "Wearables",
    sizes: [],
    date: "2025-06-02T10:00:00Z",
    bestseller: false
  },
  {
    _id: "19",
    name: "Sneakers",
    description: "Stylish sneakers for casual wear.",
    price: 1699,
    images: [assets.sneakers1, assets.sneakers2],
    category: "Footwear",
    subCategory: "Sneakers",
    sizes: ["6", "7", "8", "9", "10"],
    date: "2025-06-01T10:00:00Z",
    bestseller: true
  },
  {
    _id: "20",
    name: "Silk Scarf",
    description: "Elegant silk scarf for women.",
    price: 799,
    images: [assets.scarf1, assets.scarf2],
    category: "Accessories",
    subCategory: "Scarves",
    sizes: [],
    date: "2025-05-31T10:00:00Z",
    bestseller: false
  }
];
